export const initialState = {
    detail: {
        firstName: '',
        lastName: '',
        mobile: '',
        email: '',
        countryId: null,
        addresses: [],
        socialMediaId: null,
        platform: null,
        vehicles: []
    },
    passwordScore: 0,
    address: {
        addressId: '',
        customerId: '',
        line1: '',
        line2: '',
        cityId: '',
        zipCode: '',
        title: '',
        latitude: null,
        longitude: null,
    },
    token: null,
    tokenExpire: null,
    selectedVehicle: {},
    selectedCountry: {},
    isOrderCompleted: false,
    recentViewedProducts: [],
    wishlist: [],
    direction: 'rtl',
    isShippingCompleted: false,
    isPaymentCompleted: false,
    defaultLang: 'ar',
    quotations: {
        pending: [],
        completed: []
    },
    isModalAddToCart: false,
    isQuotationorderCompleted: true,
    isLoading: false,
    isValidcreditCard: false,
    modalLogin: false,
    checkLoginCheckout: false,
    checkLoginQuotationOrder: false,
    quotationOrderInfo: []
}
